# base image
FROM node:14-alpine

# set working directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# add `/usr/src/app/node_modules/.bin` to $PATH
ENV PATH /usr/src/app/node_modules/.bin:$PATH

# Copy npm config
COPY docker/.npmrc /root/.npmrc

# add app
COPY . /usr/src/app

# install and cache app dependencies
RUN npm install
